services:
  api:
    extends:
      file: docker-compose.yml
      service: api

  web:
    extends:
      file: docker-compose.yml
      service: web
    environment:
      - API_URL=$SERVICE_FQDN_API
