services:
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    container_name: swarmy-api
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./services/web/Dockerfile
    container_name: swarmy-web
    restart: unless-stopped
    environment:
      - API_URL=$SERVICE_FQDN_API
