services:
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    container_name: swarmy-api
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./services/web/Dockerfile
    container_name: swarmy-web
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - api
