services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    ports: []

  web:
    extends:
      file: docker-compose.yml
      service: web
    ports: []
    environment:
      - API_URL=$SERVICE_FQDN_API
