services:
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    container_name: swarmy-api
    restart: unless-stopped
    ports:
      - 4000:3000

  web:
    build:
      context: .
      dockerfile: ./services/web/Dockerfile
    container_name: swarmy-web
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 3000:3000
