services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    environment:
      - SERVICE_FQDN_API

  web:
    extends:
      file: docker-compose.yml
      service: web
    depends_on:
      - api
    environment:
      - API_URL=$SERVICE_FQDN_API
