services:
  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    container_name: swarmy-api
    restart: unless-stopped
    ports:
      - 3000:3000

  web:
    build:
      context: .
      dockerfile: ./services/web/Dockerfile
    container_name: swarmy-web
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 80:4321
