api:
  dashboard: true
  debug: true

certificatesResolvers:
  cloudflare:
    acme:
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
      storage: /etc/traefik/acme.json

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

log:
  level: info

ping:
  entryPoint: http

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
